### ISSUE TITLE
The element is dragged slowly

### ISSUE THREAD

**Issue by watermellon2018** [STRML/react-grid-layout#1273] opened 2020-08-27 06:56 UTC
When dragging element it change position slowly. It hangs a little

**Comment by ggcatu** [comment] 2020-08-28 16:06
Is it something like this ? https://github.com/STRML/react-grid-layout/issues/1265

**Comment by watermellon2018** [comment] 2020-09-04 05:54
yes

**Comment by STRML** [comment] 2020-09-16 13:16
Closing as duplicate of #1265

**Closed by STRML** 2020-09-16 13:16 UTC
