### ISSUE TITLE
0.16.1 breaks onLayoutChange

### ISSUE THREAD

**Issue by rogueturnip** [STRML/react-grid-layout#683] opened 2017-12-11 23:58 UTC
- [ ] Bug

I was doing testing with 0.15.2 and it worked that the layout got saved into localstorage via onLayoutChange after dragging or resizing, now it doesn't call the onLayoutChange callback when the items are moved or resized.  If this was changed for another callback please let me know.  It was working great in responsive before but 0.16.1 breaks it.

**Comment by KevinJunJun** [comment] 2017-12-12 08:49
I have the same problem

**Comment by frazboyz** [comment] 2017-12-12 20:36
Duplicate of #670

**Comment by oyshan** [comment] 2017-12-13 07:53
Same here

**Comment by HyczZhu** [comment] 2017-12-14 09:00
I noticed that the compact function in utils.js no longer clones the layout items at 0.16.1, which makes the references of the layout items never change.
When layout is changed, all the changes are applied the same layout item object in state.oldLayout, which makes the oldLayout is always the same as newlayout, and the onLayoutChange will not be triggered.

see:
https://github.com/STRML/react-grid-layout/blob/0.16.0/lib/utils.js#L108
https://github.com/STRML/react-grid-layout/blob/0.16.1/lib/utils.js#L109

**Comment by STRML** [comment] 2017-12-14 13:37
Indeed - that is a bug. I'll want to get a regression test in here first before we fix it.

**Closed** 2017-12-17 15:34 UTC

**Comment by STRML** [comment] 2017-12-17 15:38
`0.16.2`
