### ISSUE TITLE
How to use element position fixed in widget?

### ISSUE THREAD

**Issue by emirdeliz** [STRML/react-grid-layout#536] opened 2017-04-14 21:22 UTC
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

Hi, how to use an element with the fixed position in the widget? I tried display calendar with position fixed and z-index 9999, but not works. See the image.

![tt](https://cloud.githubusercontent.com/assets/6270495/25056419/127000c0-213f-11e7-9a52-6330f5e6391c.png)

**Comment by svancise** [comment] 2017-06-08 12:15
@emirdeliz, did you find a way around this issue?

**Comment by Mess1ah** [comment] 2017-06-29 12:42
I guess it is caused by transform and z-index problem.

**Comment by jsnelgro** [comment] 2017-11-23 18:17
I think this should be marked as a bug. It looks like the transform is applied as an inline style, which makes it difficult to override.

**Comment by STRML** [comment] 2017-11-23 18:27
Set `useCSSTransforms: false` in props.

**Comment by vacom** [comment] 2018-03-07 19:07
@STRML thanks, it fixes the issue. This issue can be closed.

**Closed** 2018-03-07 21:31 UTC
