### ISSUE TITLE
Doesn't render layout on mentioned breakpoint values

### ISSUE THREAD

**Issue by anvesh-xactly** [STRML/react-grid-layout#501] opened 2017-02-27 06:32 UTC
I used the default responsive HOC to render a responsive layout. My breakpoints are 1200, 996, 768 for lg, md & sm. However, while simple testing, I found out the UI will not change on specified values. Rather it goes off the mark like 50-100px at each breakpoint stop and then renders new layout.

For example, a 'md' screen breakpoint should change layout at 996/997px, but not on 1060px or 1020px. Why does it happen like this?

- [x] Bug
- [ ] Feature Request
- [ ] Question

Here is the WebpackBin Template for the corresponding bug.
http://www.webpackbin.com/V1iIRintG

Open developer tools console and notice the log messages that prints the breakpoints sizes.

Please advise.

**Comment by daynin** [comment] 2019-10-09 07:00
I can't reproduce it so I'll close it for now

**Closed by daynin** 2019-10-09 07:00 UTC
