### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#151] opened 2016-02-10 11:36 UTC
I'm getting "Maximum call stack size exceeded" since I upgraded, so somewhere, there seems to be a recursive call causing issues... Looking into it further.

This is using the responsive RGL, v0.10.1.

**Comment by STRML** [comment] 2016-02-10 21:24
Could you check if this is fixed in 0.10.2?

**Comment by Puffton** [comment] 2016-02-10 23:59
Thanks for the quick response, seems to work now!

**Comment by Puffton** [comment] 2016-02-14 15:22
This issue is back for me in 0.10.6: Uncaught RangeError: Maximum call stack size exceeded

**Comment by STRML** [comment] 2016-02-14 15:24
Could you please post the stack?

**Comment by Puffton** [comment] 2016-02-14 15:28
**This x1:**
ReactMultiChild.Mixin.updateChildren @ bundle.min.js:530ReactDOMComponent.Mixin._updateDOMChildren @ bundle.min.js:427ReactDOMComponent.Mixin.updateComponent @ bundle.min.js:427ReactDOMComponent.Mixin.receiveComponent @ bundle.min.js:427ReactReconciler.receiveComponent @ bundle.min.js:567ReactCompositeComponentMixin._updateRenderedComponent @ bundle.min.js:413ReactCompositeComponentMixin._performComponentUpdate @ bundle.min.js:413ReactCompositeComponentMixin.updateComponent @ bundle.min.js:413a @ bundle.min.js:552ReactCompositeComponentMixin.performUpdateIfNecessary @ bundle.min.js:413ReactReconciler.performUpdateIfNecessary @ bundle.min.js:567
3bundle.min.js:413 Uncaught RangeError: Maximum call stack size exceededReactCompositeComponentMixin._checkPropTypes @ bundle.min.js:413ReactCompositeComponentMixin._processProps @ bundle.min.js:413ReactCompositeComponentMixin.updateComponent @ bundle.min.js:413a @ bundle.min.js:552ReactCompositeComponentMixin.receiveComponent @ bundle.min.js:413ReactReconciler.receiveComponent @ bundle.min.js:567ReactCompositeComponentMixin._updateRenderedComponent @ bundle.min.js:413ReactCompositeComponentMixin._performComponentUpdate @ bundle.min.js:413ReactCompositeComponentMixin.updateComponent @ bundle.min.js:413a @ bundle.min.js:552ReactCompositeComponentMixin.receiveComponent @ bundle.min.js:413ReactReconciler.receiveComponent @ bundle.min.js:567

**This x3:**
ReactCompositeComponentMixin._checkPropTypes	@	bundle.min.js:413
ReactCompositeComponentMixin._processProps	@	bundle.min.js:413
ReactCompositeComponentMixin.updateComponent	@	bundle.min.js:413
a	@	bundle.min.js:552
ReactCompositeComponentMixin.receiveComponent	@	bundle.min.js:413
ReactReconciler.receiveComponent	@	bundle.min.js:567
ReactCompositeComponentMixin._updateRenderedComponent	@	bundle.min.js:413
ReactCompositeComponentMixin._performComponentUpdate	@	bundle.min.js:413
ReactCompositeComponentMixin.updateComponent	@	bundle.min.js:413
a	@	bundle.min.js:552
ReactCompositeComponentMixin.receiveComponent	@	bundle.min.js:413
ReactReconciler.receiveComponent	@	bundle.min.js:567

**Comment by STRML** [comment] 2016-02-14 15:45
Hmm. That stack isn't deep enough to show any RGL code, so I can't really debug it.

**Comment by Puffton** [comment] 2016-02-14 22:43
Got a longer stack trace in Safari:

[Error] RangeError: Maximum call stack size exceeded.
	traverseAllChildrenImpl
	traverseAllChildrenImpl
	traverseAllChildren
	flattenChildren
	_reconcilerUpdateChildren
	_updateChildren
	updateChildren
	_updateDOMChildren
	updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	updateChildren
	_reconcilerUpdateChildren
	_updateChildren
	updateChildren
	_updateDOMChildren
	updateComponent
	receiveComponent
	receiveComponent
	updateChildren
	_reconcilerUpdateChildren
	_updateChildren
	updateChildren
	_updateDOMChildren
	updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	performUpdateIfNecessary
	performUpdateIfNecessary
	runBatchedUpdates
	perform
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	close
	closeAll
	perform
	perform
	flushBatchedUpdates

**Comment by adarshk** [comment] 2016-02-21 20:53
I am getting the same error on both 0.10.7 and 0.10.8. @Puffton did you figure out what the problem was? I was not getting this when I was using pre 0.10.0 or on beta.

**Comment by Puffton** [comment] 2016-02-21 22:09
@adarshk didn't manage to find the issue yet, haven't had time to look into it deeply. My potential causes were firing my own events or using the PureRenderMixin, but neither seemed to be the trigger judging by my quick experiments.

**Comment by kibs** [comment] 2016-03-02 06:00
I got the error because i was listening on onLayoutChange which would set the allLayouts into state, which again would be provided using the layouts property, like a controlled input works.

This caused the ResponsiveGridLayout to recalculate the layouts, and trigger onLayoutChange again. Creating a loop.

**Closed** 2016-05-03 20:54 UTC

**Comment by chenkehxx** [comment] 2016-05-26 09:23
I have the same issue, does it fixed? my RGL version is: 0.12.4.

**Comment by XeniaSiskaki** [comment] 2018-01-25 15:21
The error can be reproduced in the [WebpackBin Editable demo](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI) from the docs. 

Steps to reproduce:
* Create a layout with compaction type vertical that contains at least one static element
* Select an element and drag it over the static element
* Without letting the element, drag it around the static element (top and bottom)

**Comment by kylietmo** [comment] 2018-09-25 23:13
Having problems with this in version 0.16.6 still as described in #859. Any ideas?

**Comment by ACPrice** [comment] 2018-10-15 22:28
Also having issues with this in `0.16.0`. I'm going to try upgrading to `0.16.6`, but expect to encounter the issue there, too, per @kylietmo

**Comment by moustastrophe** [comment] 2019-05-24 09:06
Was there ever a fix for this? I'm getting it too, exactly as per @XeniaSiskaki mentions

**Comment by yipei1028** [comment] 2021-03-31 10:05
> I got the error because i was listening on onLayoutChange which would set the allLayouts into state, which again would be provided using the layouts property, like a controlled input works.
> 
> This caused the ResponsiveGridLayout to recalculate the layouts, and trigger onLayoutChange again. Creating a loop.

Hi @kibs ,

I am facing the same situation as you mentioned.
Would you mind sharing tips of your solution?

Thanks,
Yi-Pei

**Comment by GourabPaul007** [comment] 2022-06-02 06:10
It is still an issue on version 1.3.4 when I set the layout using `setLayout(layout)`, it detects a layout change & calls the function again. 
Is there a way to fix or bypass this? Ive been using `onDragStop` & `onResizeStop` but it doesn't update the x & y values of the new item that it dynamically added.
