### ISSUE TITLE
RGL doesn't play well with StrictMode

### ISSUE THREAD

**Issue by daviesgeek** [STRML/react-grid-layout#1397] opened 2021-02-02 17:58 UTC
RGL doesn't play well with strict mode. Here's a quick sandbox to demonstrate: https://codesandbox.io/s/adoring-austin-8929c?file=/src/index.js

In my project, I'm seeing this error:

![RGL strict mode error](https://user-images.githubusercontent.com/2348508/106642461-3914b180-653d-11eb-8003-8ed15320de9b.png)

I'm not sure why I'm not getting the same error, but the end result is that strict mode & RGL don't exactly play well.

**Comment by matthew-davies-hrp** [comment] 2021-02-04 16:40
This is a duplicate of #1091, but #1091 was auto closed

**Comment by daviesgeek** [comment] 2021-02-04 16:42
This is a duplicate of #1091, but that’s been auto closed, so keeping this open for now

**Closed** 2021-02-04 17:02 UTC

**Comment by daviesgeek** [comment] 2021-02-04 17:04
Thanks, I’m looking at properly fixing this right now, basically updating the PR linked in #1091

**Comment by STRML** [comment] 2021-02-04 17:05
Thanks, that would be very helpful.

**Comment by daviesgeek** [comment] 2021-02-04 17:11
Ahhh okay good to know. I’m just now familiarizing myself with the code base and trying to get a sense of what’s going on and how to fix it.

**Comment by STRML** [comment] 2021-03-16 17:23
Fixed and released in `1.2.3`.
