### ISSUE TITLE
Drag item "into" another item

### ISSUE THREAD

**Issue by spdaly** [STRML/react-grid-layout#305] opened 2016-08-02 17:31 UTC
I was wondering if anyone has extended this solution to do nesting.  Drag one container into another.

I'm trying to build an app that people can use to categorize information into  "stacks."  You would drag on item over another to create a stack.  And then "unstack" by dragging items out.

**Comment by STRML** [comment] 2016-10-03 19:06
Duplicate of #289.

**Closed by STRML** 2016-10-03 19:06 UTC
