### ISSUE TITLE
autoSize doesn't work, either throws warnings or fails to resize to fit interior.

### ISSUE THREAD

**Issue by HeroicAutodidact** [STRML/react-grid-layout#490] opened 2017-02-16 20:25 UTC
I have a react-layout-grid I'm creating with the following command: 

`React.createElement(ReactGridLayout, {layout: layout, rowHeight: 20, width: this.props.totalWidth, autoSize:true}, framedTiles);`

The layout object is full of "GridDataItems" (not sure what to call these) of the form: 
```
{
      i:String(root.editorState.tileIdCounter),
      y:20,
      x:0,
      isDraggable: true,
      isResizable: true,
      w: 4
} 
```

And the ReactGridLayout's children are plain divs containing (diverse) custom components which may resize themselves dynamically. 
```
<div key={child.key}
             style={{
               borderRadius: 5,
               borderStyle: 'solid',
               borderWidth:'thin',
               borderColor: '#111111',
               padding: 12,
               background: '#AAAAAA'
             }}>
          {child}
        </div>
```

I'm expecting autoSize to take care of resizing the height, which it _does_ when I leave out the `h` attribute of layout GridDataItems. To be clear, I'm getting the desired behavior with this code, but I'm also getting a warning: 

```
Warning: Failed prop type: The prop `h` is marked as required in `GridItem`, but its value is `undefined`.
    in GridItem (created by ReactGridLayout)
    in ReactGridLayout (created by LayoutEditor)
    in LayoutEditor (created by Connect(LayoutEditor))
    in Connect(LayoutEditor) (created by ProblemEditRoot)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by ProblemEditRoot)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by ProblemEditRoot)
    in ProblemEditRoot
    in MuiThemeProvider
    in Provider
```

If I _do_ include h, the GridItem does not stretch to the size of its contents, but instead uses the arbitrary h (which can be smaller than the interior component).

**Comment by HeroicAutodidact** [comment] 2017-02-16 20:31
Actually, scratch that, when I remove h, it works as expected to dynamically resize the first item, but it will not accept more items added to the ReactGridLayout.

**Comment by williamgranli** [comment] 2017-03-23 10:16
@HeroicAutodidact Did you manage to solve this? I want a simple solution where the grid items resize according to content, but leaving out h in the grid item's config/props doesn't seem like a good solution since it throws props validation errors and basically renders all functionality after the initial render useless.

**Comment by stanleycyang** [comment] 2017-03-26 06:50
+1

**Comment by nehero** [comment] 2017-04-17 20:08
+1 getting 

`Warning: Failed prop type: ReactGridLayout: layout[0].h must be a number!`

When I omit `h`

**Comment by STRML** [comment] 2017-04-17 20:24
`autoSize` does *not* support autosizing items, just the container.

From the docs:

```
// If true, the container height swells and contracts to fit contents
autoSize: ?boolean = true,
```

This is a feature request, not a bug. As such I'll close this; I am of course accepting PRs if you can get the functionality to work (it is quite involved; you'll have to measure and track resizes of every single item). It may be possible via plugin in 2.0.

**Closed by STRML** 2017-04-17 20:24 UTC
