### ISSUE TITLE
Create new tile by dragging from topbar

### ISSUE THREAD

**Issue by rickyhan** [STRML/react-grid-layout#390] opened 2016-10-28 09:31 UTC
Is it possible to create a new predefined tile of width w and height h by dragging off a sidebar? I know this is possible and just wondering if anyone had got the wheel to work so I won't have to reinvent it.

I'm thinking about doing the following:
1. create a new griditem and bind it to Infinity, Infinity in layouts
2. somehow trigger onDragStart
3. then update layouts onDragStop

Thanks in advance.

**Comment by STRML** [comment] 2016-11-14 14:31
This is not a bug or feature request so I am going to close it, but I recommend trying out Gitter or IRC for these kind of more open-ended questions.

At this point in time there is no first-party support for this, although this is a use case I will keep in mind for #346.

**Closed by STRML** 2016-11-14 14:31 UTC
